- id: '1589336778998'
  alias: Night Time
  description: Lights are more pleasing at night
  trigger:
  - event: sunset
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - scene: scene.night_time
  - delay: 00:00:05
  - data: {}
    entity_id: light.pete_s_room_zha_group_0x0002
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
  - data: {}
    entity_id: light.living_room_zha_group_0x0001
    service: light.turn_off
  - data: {}
    entity_id: light.matt_s_room_zha_group_0x0004
    service: light.turn_off
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_off
  - data:
      name: Google Dark Theme
    service: frontend.set_theme
- id: '1589337275613'
  alias: Day Time
  description: ''
  trigger:
  - event: sunrise
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - scene: scene.day_time
  - delay: 00:00:05
  - data: {}
    entity_id: light.pete_s_room_zha_group_0x0002
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
  - data: {}
    entity_id: light.living_room_zha_group_0x0001
    service: light.turn_off
  - data: {}
    entity_id: light.matt_s_room_zha_group_0x0004
    service: light.turn_off
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_off
  - data:
      name: Google Light Theme
    service: frontend.set_theme
- id: '1589340001071'
  alias: Wyze Test
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_778f9400
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 51bdf0633cdc4a8087543c1e6699fca8
    domain: light
    entity_id: light.ledvance_a19_rgbw_1fcc0100_level_light_color_on_off
    type: turn_on
  - device_id: 69431b1609244883b1836b44878691ea
    domain: light
    entity_id: light.ledvance_a19_rgbw_1b3c0100_level_light_color_on_off
    type: turn_on
- id: '1589344256486'
  alias: Dez Feeder
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_c7795a719
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Dez fed
    service: notify.notify_cat_group
- id: '1589405609003'
  alias: Maddie Feeder
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_c77956b95
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Maddie fed
    service: notify.notify_cat_group
- id: '1589405839821'
  alias: Mom's autolights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_c77844009
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_on
  - delay: 00:03:02
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_off
- id: '1589406491402'
  alias: Basement Hallway Autolights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_m778f9400
    for: 00:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.basement_light_2
    service: light.turn_on
  - delay: 00:05:00
  - data: {}
    entity_id: light.basement_light_2
    service: light.turn_off
- id: '1589503644352'
  alias: Upstairs Hallway Autolights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_m77850632
    for: 00:00:05
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_on
  - delay: 00:02:00
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
- id: '1589509801065'
  alias: Matt's Automations
  description: ''
  trigger:
  - platform: webhook
    webhook_id: shortcuts_call_service
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.json.entity_id }}'
    service_template: '{{ trigger.json.service }}'
- id: '1589550293183'
  alias: Opensky Notifications
  description: ''
  trigger:
  - event_data: {}
    event_type: opensky_entry
    platform: event
  condition: []
  action:
  - data:
      message: 'Flight entry of {{ trigger.event.data.callsign }} '
    service: notify.mobile_app_pixel_3_xl
  - data:
      message: 'Flight entry of {{ trigger.event.data.callsign }} '
    service: notify.notify_me
