- id: '1589336778998'
  alias: Night Time
  description: Lights are more pleasing at night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.night_time
  - delay: 00:00:05
  - data: {}
    entity_id: light.pete_s_room_zha_group_0x0002
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
  - data: {}
    entity_id: light.living_room_zha_group_0x0001
    service: light.turn_off
  - data: {}
    entity_id: light.matt_s_room_zha_group_0x0004
    service: light.turn_off
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_bathroom_zha_group_0x0006
    service: light.turn_off
  - data:
      name: Google Dark Theme
    service: frontend.set_theme
- id: '1589337275613'
  alias: Day Time
  description: ''
  trigger:
  - event: sunrise
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - scene: scene.day_time
  - delay: 00:00:05
  - data: {}
    entity_id: light.pete_s_room_zha_group_0x0002
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
  - data: {}
    entity_id: light.living_room_zha_group_0x0001
    service: light.turn_off
  - data: {}
    entity_id: light.matt_s_room_zha_group_0x0004
    service: light.turn_off
  - data: {}
    entity_id: light.mom_s_light_2
    service: light.turn_off
  - data: {}
    entity_id: light.upstairs_bathroom_zha_group_0x0006
    service: light.turn_off
  - data:
      name: Google Light Theme
    service: frontend.set_theme
- id: '1589344256486'
  alias: Basement Dez Feeder
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_dez
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Dez fed
    service: notify.notify_cat_group
- id: '1589405609003'
  alias: Basement Maddie Feeder
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_maddie
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Maddie fed
    service: notify.notify_cat_group
- id: '1589405839821'
  alias: Mom's autolights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_mom_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.mom_s_step_light
    service: light.turn_on
  - delay: 00:03:00
  - data: {}
    entity_id: light.mom_s_step_light
    service: light.turn_off
- id: '1589406491402'
  alias: Basement Hallway Autolights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_motion_basement_hall
    for: 00:00:02
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.basement_hall_light
    service: light.turn_on
  - data: {}
    entity_id: switch.zigbee_basement_steps
    service: switch.turn_on
  - delay: 00:10:00
  - data: {}
    entity_id: light.basement_hall_light
    service: light.turn_off
  - data: {}
    entity_id: switch.zigbee_basement_steps
    service: switch.turn_off
- id: '1589503644352'
  alias: Upstairs Hallway Autolights ON
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_motion_upstairs_hall
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:00:00'
    before: 07:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_on
- id: '1589509801065'
  alias: Matt's Automations
  description: ''
  trigger:
  - platform: webhook
    webhook_id: shortcuts_call_service
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.json.entity_id }}'
    service_template: '{{ trigger.json.service }}'
- id: '1589550293183'
  alias: Opensky Notifications
  description: ''
  trigger:
  - event_data: {}
    event_type: opensky_entry
    platform: event
  condition: []
  action:
  - data:
      message: 'Flight entry of {{ trigger.event.data.callsign }} '
    service: notify.mobile_app_pixel_3_xl
  - data:
      message: 'Flight entry of {{ trigger.event.data.callsign }} '
    service: notify.notify_me
- id: '1590006243895'
  alias: Basement UB and Workshop Autolights ON
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_basement_unfinished
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.workshop
    service: light.turn_on
  - data: {}
    entity_id: switch.zigbee_unfinished_basement
    service: switch.turn_on
- id: '1590006733034'
  alias: ' Basement UB and Workshop Autolights OFF'
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_basement_unfinished
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.workshop
    service: light.turn_off
  - data: {}
    entity_id: switch.zigbee_unfinished_basement
    service: switch.turn_off
- id: '1590007455630'
  alias: Toilet Autolights ON
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_toilet
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_on
- id: '1590007543292'
  alias: Toilet Autolights OFF
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_toilet
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.toilet_light
    service: light.turn_off
- id: '1590008723151'
  alias: Guest Bathroom Autolights ON
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_guest_bath
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.guest_bath
    service: light.turn_on
- id: '1590008765314'
  alias: Guest Bathroom Autolights OFF
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_guest_bath
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.guest_bath
    service: light.turn_off
- id: '1590009850077'
  alias: Basement Study Autolights ON
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_study
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.zigbee_study
    service: switch.turn_on
- id: '1590009971251'
  alias: Basement Study Autolights OFF
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_contact_study
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.zigbee_study
    service: switch.turn_off
- id: '1590248187373'
  alias: Upstairs Hallway Autolights OFF
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_motion_upstairs_hall
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '20:00:00'
    before: 07:00:00
    condition: time
  action:
  - data: {}
    entity_id: light.upstairs_hallway_zha_group_0x0003
    service: light.turn_off
